FROM node:24 AS build

WORKDIR /app
COPY package.json package-lock.json tsconfig.base.json tsconfig.json ./
COPY backend ./backend
COPY frontend/package.json ./frontend/package.json
COPY infra/package.json ./infra/package.json
COPY packages ./packages
RUN npm ci
RUN npm run build:contracts && npm run build -w @app/backend

FROM public.ecr.aws/lambda/nodejs:24

WORKDIR ${LAMBDA_TASK_ROOT}
COPY package.json package-lock.json ./
COPY backend/package.json ./backend/package.json
COPY frontend/package.json ./frontend/package.json
COPY infra/package.json ./infra/package.json
COPY packages/zod/package.json ./packages/zod/package.json
COPY packages/cucumber/package.json ./packages/cucumber/package.json
RUN npm ci --omit=dev
COPY --from=build /app/backend/dist ./backend/dist
COPY --from=build /app/packages/zod/dist ./packages/zod/dist
COPY --from=build /app/packages/zod/seeds ./packages/zod/seeds
CMD ["backend/dist/lambda.handler"]
