import { z } from 'zod';

import {
  editableListItemSchema,
  editableListSchema,
  editableObjectSchema,
  editableValueSchema,
  entityIdSchema,
  pageIdSchema,
  type EditableValue,
  type EntityId,
  type PageId,
} from './content.js';
import legacyVisibleContentSeeds from '../seeds/legacy-visible-content.json' with { type: 'json' };
import { homeV2SeedData } from '../seeds/home.js';
import type { EntityEditorDefinition } from './editor-contracts.js';
import { mergeEntityModules } from './editor-contracts.js';
import { homeEntityModule } from './home.js';
import { propertyManagementEntityModule } from './property-management.js';
import { propertyManagementV2SeedData } from '../seeds/property-management.js';
import { storageEntityModule } from './storage.js';
import { storageV2SeedData } from '../seeds/storage.js';

export const entityKindSchema = z.enum(['object', 'list']);

export const iconNameSchema = z.enum([
  'Award',
  'BarChart3',
  'Boxes',
  'Building',
  'Building2',
  'Calculator',
  'ClipboardCheck',
  'Clock',
  'CreditCard',
  'DollarSign',
  'Facebook',
  'FileCheck',
  'FileText',
  'Handshake',
  'HardHat',
  'Heart',
  'Home',
  'Instagram',
  'Key',
  'Landmark',
  'LineChart',
  'Linkedin',
  'MapPin',
  'MessageSquare',
  'Monitor',
  'Mountain',
  'Search',
  'Settings',
  'Shield',
  'ShoppingBag',
  'Shovel',
  'Target',
  'TrendingUp',
  'Twitter',
  'Users',
  'Wallet',
  'Warehouse',
  'Wrench',
]);

export const managedImageReferenceSchema = z.strictObject({
  kind: z.literal('managed'),
  key: z.string().trim().min(1).max(1_024),
});

export const externalImageReferenceSchema = z.strictObject({
  kind: z.literal('external'),
  url: z.url().refine((url) => url.startsWith('https://'), 'External images must use HTTPS'),
});

export const imageReferenceSchema = z.discriminatedUnion('kind', [
  managedImageReferenceSchema,
  externalImageReferenceSchema,
]);

export interface EntityDefinition {
  readonly id: EntityId;
  readonly pageId: PageId;
  readonly kind: z.infer<typeof entityKindSchema>;
  readonly label: string;
  readonly publicPath: readonly string[];
  readonly schema: z.ZodType;
  readonly listItemSchema?: z.ZodType;
  /** Present only after this entity has an explicit version-2 semantic editing contract. */
  readonly editor?: EntityEditorDefinition;
}

export interface PageDefinition {
  readonly id: PageId;
  readonly route: string;
  readonly s3Key: string;
  readonly entities: readonly EntityDefinition[];
}

const definitions = [
  {
    id: 'home.anniversary-banner',
    pageId: 'home',
    kind: 'object',
    label: 'Anniversary Banner',
    publicPath: ['home', 'anniversary-banner'],
    schema: editableObjectSchema,
  },
  {
    id: 'home.header.brand',
    pageId: 'home',
    kind: 'object',
    label: 'Header Brand',
    publicPath: ['home', 'header', 'brand'],
    schema: editableObjectSchema,
  },
  {
    id: 'home.hero',
    pageId: 'home',
    kind: 'object',
    label: 'Hero',
    publicPath: ['home', 'hero'],
    schema: editableObjectSchema,
  },
  {
    id: 'home.divisions.header',
    pageId: 'home',
    kind: 'object',
    label: 'Divisions Header',
    publicPath: ['home', 'divisions', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'home.divisions.items',
    pageId: 'home',
    kind: 'list',
    label: 'Divisions Items',
    publicPath: ['home', 'divisions', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'home.core-values.header',
    pageId: 'home',
    kind: 'object',
    label: 'Core Values Header',
    publicPath: ['home', 'core-values', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'home.core-values.items',
    pageId: 'home',
    kind: 'list',
    label: 'Core Values Items',
    publicPath: ['home', 'core-values', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'home.journey.header',
    pageId: 'home',
    kind: 'object',
    label: 'Journey Header',
    publicPath: ['home', 'journey', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'home.journey.timeline',
    pageId: 'home',
    kind: 'list',
    label: 'Journey Timeline',
    publicPath: ['home', 'journey', 'timeline'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'home.leadership.header',
    pageId: 'home',
    kind: 'object',
    label: 'Leadership Header',
    publicPath: ['home', 'leadership', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'home.leadership.members',
    pageId: 'home',
    kind: 'list',
    label: 'Leadership Members',
    publicPath: ['home', 'leadership', 'members'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'home.news.header',
    pageId: 'home',
    kind: 'object',
    label: 'News Header',
    publicPath: ['home', 'news', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'home.news.items',
    pageId: 'home',
    kind: 'list',
    label: 'News Items',
    publicPath: ['home', 'news', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'home.careers.header',
    pageId: 'home',
    kind: 'object',
    label: 'Careers Header',
    publicPath: ['home', 'careers', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'home.careers.open-positions',
    pageId: 'home',
    kind: 'list',
    label: 'Careers Open Positions',
    publicPath: ['home', 'careers', 'open-positions'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'home.careers.resume-intro',
    pageId: 'home',
    kind: 'object',
    label: 'Careers Resume Intro',
    publicPath: ['home', 'careers', 'resume-intro'],
    schema: editableObjectSchema,
  },
  {
    id: 'home.contact',
    pageId: 'home',
    kind: 'object',
    label: 'Contact',
    publicPath: ['home', 'contact'],
    schema: editableObjectSchema,
  },
  {
    id: 'home.footer',
    pageId: 'home',
    kind: 'object',
    label: 'Footer',
    publicPath: ['home', 'footer'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.anniversary-banner',
    pageId: 'property-management',
    kind: 'object',
    label: 'Anniversary Banner',
    publicPath: ['property-management', 'anniversary-banner'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.header',
    pageId: 'property-management',
    kind: 'object',
    label: 'Header',
    publicPath: ['property-management', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.hero',
    pageId: 'property-management',
    kind: 'object',
    label: 'Hero',
    publicPath: ['property-management', 'hero'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.hero.stats',
    pageId: 'property-management',
    kind: 'list',
    label: 'Hero Stats',
    publicPath: ['property-management', 'hero', 'stats'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.services.header',
    pageId: 'property-management',
    kind: 'object',
    label: 'Services Header',
    publicPath: ['property-management', 'services', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.services.items',
    pageId: 'property-management',
    kind: 'list',
    label: 'Services Items',
    publicPath: ['property-management', 'services', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.process.header',
    pageId: 'property-management',
    kind: 'object',
    label: 'Process Header',
    publicPath: ['property-management', 'process', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.process.steps',
    pageId: 'property-management',
    kind: 'list',
    label: 'Process Steps',
    publicPath: ['property-management', 'process', 'steps'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.portfolio.managed.header',
    pageId: 'property-management',
    kind: 'object',
    label: 'Portfolio Managed Header',
    publicPath: ['property-management', 'portfolio', 'managed', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.portfolio.managed.items',
    pageId: 'property-management',
    kind: 'list',
    label: 'Portfolio Managed Items',
    publicPath: ['property-management', 'portfolio', 'managed', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.portfolio.coas.header',
    pageId: 'property-management',
    kind: 'object',
    label: 'Portfolio Coas Header',
    publicPath: ['property-management', 'portfolio', 'coas', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.portfolio.coas.items',
    pageId: 'property-management',
    kind: 'list',
    label: 'Portfolio Coas Items',
    publicPath: ['property-management', 'portfolio', 'coas', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.portfolio.hoas.header',
    pageId: 'property-management',
    kind: 'object',
    label: 'Portfolio Hoas Header',
    publicPath: ['property-management', 'portfolio', 'hoas', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.portfolio.hoas.items',
    pageId: 'property-management',
    kind: 'list',
    label: 'Portfolio Hoas Items',
    publicPath: ['property-management', 'portfolio', 'hoas', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.tenant-portal',
    pageId: 'property-management',
    kind: 'object',
    label: 'Tenant Portal',
    publicPath: ['property-management', 'tenant-portal'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.tenant-portal.features',
    pageId: 'property-management',
    kind: 'list',
    label: 'Tenant Portal Features',
    publicPath: ['property-management', 'tenant-portal', 'features'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.team.header',
    pageId: 'property-management',
    kind: 'object',
    label: 'Team Header',
    publicPath: ['property-management', 'team', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.team.members',
    pageId: 'property-management',
    kind: 'list',
    label: 'Team Members',
    publicPath: ['property-management', 'team', 'members'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.about',
    pageId: 'property-management',
    kind: 'object',
    label: 'About',
    publicPath: ['property-management', 'about'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.about.features',
    pageId: 'property-management',
    kind: 'list',
    label: 'About Features',
    publicPath: ['property-management', 'about', 'features'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.testimonials.header',
    pageId: 'property-management',
    kind: 'object',
    label: 'Testimonials Header',
    publicPath: ['property-management', 'testimonials', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.testimonials.items',
    pageId: 'property-management',
    kind: 'list',
    label: 'Testimonials Items',
    publicPath: ['property-management', 'testimonials', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.testimonials.stats',
    pageId: 'property-management',
    kind: 'list',
    label: 'Testimonials Stats',
    publicPath: ['property-management', 'testimonials', 'stats'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.faq.header',
    pageId: 'property-management',
    kind: 'object',
    label: 'Faq Header',
    publicPath: ['property-management', 'faq', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.faq.items',
    pageId: 'property-management',
    kind: 'list',
    label: 'Faq Items',
    publicPath: ['property-management', 'faq', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.careers',
    pageId: 'property-management',
    kind: 'object',
    label: 'Careers',
    publicPath: ['property-management', 'careers'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.reviews.header',
    pageId: 'property-management',
    kind: 'object',
    label: 'Reviews Header',
    publicPath: ['property-management', 'reviews', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.reviews.platforms',
    pageId: 'property-management',
    kind: 'list',
    label: 'Reviews Platforms',
    publicPath: ['property-management', 'reviews', 'platforms'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.reviews.footer',
    pageId: 'property-management',
    kind: 'object',
    label: 'Reviews Footer',
    publicPath: ['property-management', 'reviews', 'footer'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.contact.header',
    pageId: 'property-management',
    kind: 'object',
    label: 'Contact Header',
    publicPath: ['property-management', 'contact', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.contact.details',
    pageId: 'property-management',
    kind: 'object',
    label: 'Contact Details',
    publicPath: ['property-management', 'contact', 'details'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.footer.brand',
    pageId: 'property-management',
    kind: 'object',
    label: 'Footer Brand',
    publicPath: ['property-management', 'footer', 'brand'],
    schema: editableObjectSchema,
  },
  {
    id: 'property-management.footer.links',
    pageId: 'property-management',
    kind: 'list',
    label: 'Footer Links',
    publicPath: ['property-management', 'footer', 'links'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.footer.social',
    pageId: 'property-management',
    kind: 'list',
    label: 'Footer Social',
    publicPath: ['property-management', 'footer', 'social'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'property-management.footer.legal',
    pageId: 'property-management',
    kind: 'object',
    label: 'Footer Legal',
    publicPath: ['property-management', 'footer', 'legal'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.anniversary-banner',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Anniversary Banner',
    publicPath: ['real-estate', 'anniversary-banner'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.header',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Header',
    publicPath: ['real-estate', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.hero',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Hero',
    publicPath: ['real-estate', 'hero'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.hero.stats',
    pageId: 'real-estate',
    kind: 'list',
    label: 'Hero Stats',
    publicPath: ['real-estate', 'hero', 'stats'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'real-estate.listings.header',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Listings Header',
    publicPath: ['real-estate', 'listings', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.listings.items',
    pageId: 'real-estate',
    kind: 'list',
    label: 'Listings Items',
    publicPath: ['real-estate', 'listings', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'real-estate.listings.actions',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Listings Actions',
    publicPath: ['real-estate', 'listings', 'actions'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.services.header',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Services Header',
    publicPath: ['real-estate', 'services', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.services.items',
    pageId: 'real-estate',
    kind: 'list',
    label: 'Services Items',
    publicPath: ['real-estate', 'services', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'real-estate.process.header',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Process Header',
    publicPath: ['real-estate', 'process', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.process.steps',
    pageId: 'real-estate',
    kind: 'list',
    label: 'Process Steps',
    publicPath: ['real-estate', 'process', 'steps'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'real-estate.about',
    pageId: 'real-estate',
    kind: 'object',
    label: 'About',
    publicPath: ['real-estate', 'about'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.about.features',
    pageId: 'real-estate',
    kind: 'list',
    label: 'About Features',
    publicPath: ['real-estate', 'about', 'features'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'real-estate.team.header',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Team Header',
    publicPath: ['real-estate', 'team', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.team.leadership',
    pageId: 'real-estate',
    kind: 'list',
    label: 'Team Leadership',
    publicPath: ['real-estate', 'team', 'leadership'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'real-estate.team.staff',
    pageId: 'real-estate',
    kind: 'list',
    label: 'Team Staff',
    publicPath: ['real-estate', 'team', 'staff'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'real-estate.team.agents',
    pageId: 'real-estate',
    kind: 'list',
    label: 'Team Agents',
    publicPath: ['real-estate', 'team', 'agents'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'real-estate.careers',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Careers',
    publicPath: ['real-estate', 'careers'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.testimonials.header',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Testimonials Header',
    publicPath: ['real-estate', 'testimonials', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.testimonials.items',
    pageId: 'real-estate',
    kind: 'list',
    label: 'Testimonials Items',
    publicPath: ['real-estate', 'testimonials', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'real-estate.faq.header',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Faq Header',
    publicPath: ['real-estate', 'faq', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.faq.items',
    pageId: 'real-estate',
    kind: 'list',
    label: 'Faq Items',
    publicPath: ['real-estate', 'faq', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'real-estate.reviews.header',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Reviews Header',
    publicPath: ['real-estate', 'reviews', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.reviews.platforms',
    pageId: 'real-estate',
    kind: 'list',
    label: 'Reviews Platforms',
    publicPath: ['real-estate', 'reviews', 'platforms'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'real-estate.reviews.footer',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Reviews Footer',
    publicPath: ['real-estate', 'reviews', 'footer'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.contact.header',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Contact Header',
    publicPath: ['real-estate', 'contact', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.contact.details',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Contact Details',
    publicPath: ['real-estate', 'contact', 'details'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.footer.brand',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Footer Brand',
    publicPath: ['real-estate', 'footer', 'brand'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.footer.links',
    pageId: 'real-estate',
    kind: 'list',
    label: 'Footer Links',
    publicPath: ['real-estate', 'footer', 'links'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'real-estate.footer.license',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Footer License',
    publicPath: ['real-estate', 'footer', 'license'],
    schema: editableObjectSchema,
  },
  {
    id: 'real-estate.footer.legal',
    pageId: 'real-estate',
    kind: 'object',
    label: 'Footer Legal',
    publicPath: ['real-estate', 'footer', 'legal'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.anniversary-banner',
    pageId: 'construction',
    kind: 'object',
    label: 'Anniversary Banner',
    publicPath: ['construction', 'anniversary-banner'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.header',
    pageId: 'construction',
    kind: 'object',
    label: 'Header',
    publicPath: ['construction', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.hero',
    pageId: 'construction',
    kind: 'object',
    label: 'Hero',
    publicPath: ['construction', 'hero'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.hero.stats',
    pageId: 'construction',
    kind: 'list',
    label: 'Hero Stats',
    publicPath: ['construction', 'hero', 'stats'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.services.header',
    pageId: 'construction',
    kind: 'object',
    label: 'Services Header',
    publicPath: ['construction', 'services', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.services.items',
    pageId: 'construction',
    kind: 'list',
    label: 'Services Items',
    publicPath: ['construction', 'services', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.current-projects.header',
    pageId: 'construction',
    kind: 'object',
    label: 'Current Projects Header',
    publicPath: ['construction', 'current-projects', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.current-projects.category.multi-family',
    pageId: 'construction',
    kind: 'object',
    label: 'Current Projects Category Multi Family',
    publicPath: ['construction', 'current-projects', 'category', 'multi-family'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.current-projects.projects.multi-family',
    pageId: 'construction',
    kind: 'list',
    label: 'Current Projects Projects Multi Family',
    publicPath: ['construction', 'current-projects', 'projects', 'multi-family'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.current-projects.category.retail',
    pageId: 'construction',
    kind: 'object',
    label: 'Current Projects Category Retail',
    publicPath: ['construction', 'current-projects', 'category', 'retail'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.current-projects.projects.retail',
    pageId: 'construction',
    kind: 'list',
    label: 'Current Projects Projects Retail',
    publicPath: ['construction', 'current-projects', 'projects', 'retail'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.current-projects.category.office-ti',
    pageId: 'construction',
    kind: 'object',
    label: 'Current Projects Category Office Ti',
    publicPath: ['construction', 'current-projects', 'category', 'office-ti'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.current-projects.projects.office-ti',
    pageId: 'construction',
    kind: 'list',
    label: 'Current Projects Projects Office Ti',
    publicPath: ['construction', 'current-projects', 'projects', 'office-ti'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.current-projects.category.medical-dental',
    pageId: 'construction',
    kind: 'object',
    label: 'Current Projects Category Medical Dental',
    publicPath: ['construction', 'current-projects', 'category', 'medical-dental'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.current-projects.projects.medical-dental',
    pageId: 'construction',
    kind: 'list',
    label: 'Current Projects Projects Medical Dental',
    publicPath: ['construction', 'current-projects', 'projects', 'medical-dental'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.current-projects.category.industrial',
    pageId: 'construction',
    kind: 'object',
    label: 'Current Projects Category Industrial',
    publicPath: ['construction', 'current-projects', 'category', 'industrial'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.current-projects.projects.industrial',
    pageId: 'construction',
    kind: 'list',
    label: 'Current Projects Projects Industrial',
    publicPath: ['construction', 'current-projects', 'projects', 'industrial'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.current-projects.category.storage',
    pageId: 'construction',
    kind: 'object',
    label: 'Current Projects Category Storage',
    publicPath: ['construction', 'current-projects', 'category', 'storage'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.current-projects.projects.storage',
    pageId: 'construction',
    kind: 'list',
    label: 'Current Projects Projects Storage',
    publicPath: ['construction', 'current-projects', 'projects', 'storage'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.current-projects.category.subdivisions',
    pageId: 'construction',
    kind: 'object',
    label: 'Current Projects Category Subdivisions',
    publicPath: ['construction', 'current-projects', 'category', 'subdivisions'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.current-projects.projects.subdivisions',
    pageId: 'construction',
    kind: 'list',
    label: 'Current Projects Projects Subdivisions',
    publicPath: ['construction', 'current-projects', 'projects', 'subdivisions'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.current-projects.category.underground',
    pageId: 'construction',
    kind: 'object',
    label: 'Current Projects Category Underground',
    publicPath: ['construction', 'current-projects', 'category', 'underground'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.current-projects.projects.underground',
    pageId: 'construction',
    kind: 'list',
    label: 'Current Projects Projects Underground',
    publicPath: ['construction', 'current-projects', 'projects', 'underground'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.completed-projects.header',
    pageId: 'construction',
    kind: 'object',
    label: 'Completed Projects Header',
    publicPath: ['construction', 'completed-projects', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.completed-projects.category.multi-family',
    pageId: 'construction',
    kind: 'object',
    label: 'Completed Projects Category Multi Family',
    publicPath: ['construction', 'completed-projects', 'category', 'multi-family'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.completed-projects.projects.multi-family',
    pageId: 'construction',
    kind: 'list',
    label: 'Completed Projects Projects Multi Family',
    publicPath: ['construction', 'completed-projects', 'projects', 'multi-family'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.completed-projects.category.retail',
    pageId: 'construction',
    kind: 'object',
    label: 'Completed Projects Category Retail',
    publicPath: ['construction', 'completed-projects', 'category', 'retail'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.completed-projects.projects.retail',
    pageId: 'construction',
    kind: 'list',
    label: 'Completed Projects Projects Retail',
    publicPath: ['construction', 'completed-projects', 'projects', 'retail'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.completed-projects.category.office-ti',
    pageId: 'construction',
    kind: 'object',
    label: 'Completed Projects Category Office Ti',
    publicPath: ['construction', 'completed-projects', 'category', 'office-ti'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.completed-projects.projects.office-ti',
    pageId: 'construction',
    kind: 'list',
    label: 'Completed Projects Projects Office Ti',
    publicPath: ['construction', 'completed-projects', 'projects', 'office-ti'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.completed-projects.category.medical-dental',
    pageId: 'construction',
    kind: 'object',
    label: 'Completed Projects Category Medical Dental',
    publicPath: ['construction', 'completed-projects', 'category', 'medical-dental'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.completed-projects.projects.medical-dental',
    pageId: 'construction',
    kind: 'list',
    label: 'Completed Projects Projects Medical Dental',
    publicPath: ['construction', 'completed-projects', 'projects', 'medical-dental'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.completed-projects.category.industrial',
    pageId: 'construction',
    kind: 'object',
    label: 'Completed Projects Category Industrial',
    publicPath: ['construction', 'completed-projects', 'category', 'industrial'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.completed-projects.projects.industrial',
    pageId: 'construction',
    kind: 'list',
    label: 'Completed Projects Projects Industrial',
    publicPath: ['construction', 'completed-projects', 'projects', 'industrial'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.completed-projects.category.storage',
    pageId: 'construction',
    kind: 'object',
    label: 'Completed Projects Category Storage',
    publicPath: ['construction', 'completed-projects', 'category', 'storage'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.completed-projects.projects.storage',
    pageId: 'construction',
    kind: 'list',
    label: 'Completed Projects Projects Storage',
    publicPath: ['construction', 'completed-projects', 'projects', 'storage'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.completed-projects.category.subdivisions',
    pageId: 'construction',
    kind: 'object',
    label: 'Completed Projects Category Subdivisions',
    publicPath: ['construction', 'completed-projects', 'category', 'subdivisions'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.completed-projects.projects.subdivisions',
    pageId: 'construction',
    kind: 'list',
    label: 'Completed Projects Projects Subdivisions',
    publicPath: ['construction', 'completed-projects', 'projects', 'subdivisions'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.completed-projects.category.underground',
    pageId: 'construction',
    kind: 'object',
    label: 'Completed Projects Category Underground',
    publicPath: ['construction', 'completed-projects', 'category', 'underground'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.completed-projects.projects.underground',
    pageId: 'construction',
    kind: 'list',
    label: 'Completed Projects Projects Underground',
    publicPath: ['construction', 'completed-projects', 'projects', 'underground'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.plan-room.header',
    pageId: 'construction',
    kind: 'object',
    label: 'Plan Room Header',
    publicPath: ['construction', 'plan-room', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.plan-room.access-notice',
    pageId: 'construction',
    kind: 'object',
    label: 'Plan Room Access Notice',
    publicPath: ['construction', 'plan-room', 'access-notice'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.plan-room.plan-sets',
    pageId: 'construction',
    kind: 'list',
    label: 'Plan Room Plan Sets',
    publicPath: ['construction', 'plan-room', 'plan-sets'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.plan-room.request-access',
    pageId: 'construction',
    kind: 'object',
    label: 'Plan Room Request Access',
    publicPath: ['construction', 'plan-room', 'request-access'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.pros.header',
    pageId: 'construction',
    kind: 'object',
    label: 'Pros Header',
    publicPath: ['construction', 'pros', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.pros.items',
    pageId: 'construction',
    kind: 'list',
    label: 'Pros Items',
    publicPath: ['construction', 'pros', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.pros.stats',
    pageId: 'construction',
    kind: 'list',
    label: 'Pros Stats',
    publicPath: ['construction', 'pros', 'stats'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.team.header',
    pageId: 'construction',
    kind: 'object',
    label: 'Team Header',
    publicPath: ['construction', 'team', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.team.members',
    pageId: 'construction',
    kind: 'list',
    label: 'Team Members',
    publicPath: ['construction', 'team', 'members'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.workers',
    pageId: 'construction',
    kind: 'object',
    label: 'Workers',
    publicPath: ['construction', 'workers'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.about',
    pageId: 'construction',
    kind: 'object',
    label: 'About',
    publicPath: ['construction', 'about'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.about.features',
    pageId: 'construction',
    kind: 'list',
    label: 'About Features',
    publicPath: ['construction', 'about', 'features'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.bid.header',
    pageId: 'construction',
    kind: 'object',
    label: 'Bid Header',
    publicPath: ['construction', 'bid', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.careers.header',
    pageId: 'construction',
    kind: 'object',
    label: 'Careers Header',
    publicPath: ['construction', 'careers', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.careers.benefits',
    pageId: 'construction',
    kind: 'list',
    label: 'Careers Benefits',
    publicPath: ['construction', 'careers', 'benefits'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.careers.open-positions',
    pageId: 'construction',
    kind: 'list',
    label: 'Careers Open Positions',
    publicPath: ['construction', 'careers', 'open-positions'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.reviews.header',
    pageId: 'construction',
    kind: 'object',
    label: 'Reviews Header',
    publicPath: ['construction', 'reviews', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.reviews.platforms',
    pageId: 'construction',
    kind: 'list',
    label: 'Reviews Platforms',
    publicPath: ['construction', 'reviews', 'platforms'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.reviews.footer',
    pageId: 'construction',
    kind: 'object',
    label: 'Reviews Footer',
    publicPath: ['construction', 'reviews', 'footer'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.contact.header',
    pageId: 'construction',
    kind: 'object',
    label: 'Contact Header',
    publicPath: ['construction', 'contact', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.contact.details',
    pageId: 'construction',
    kind: 'object',
    label: 'Contact Details',
    publicPath: ['construction', 'contact', 'details'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.footer.brand',
    pageId: 'construction',
    kind: 'object',
    label: 'Footer Brand',
    publicPath: ['construction', 'footer', 'brand'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.footer.links',
    pageId: 'construction',
    kind: 'list',
    label: 'Footer Links',
    publicPath: ['construction', 'footer', 'links'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'construction.footer.licenses',
    pageId: 'construction',
    kind: 'object',
    label: 'Footer Licenses',
    publicPath: ['construction', 'footer', 'licenses'],
    schema: editableObjectSchema,
  },
  {
    id: 'construction.footer.legal',
    pageId: 'construction',
    kind: 'object',
    label: 'Footer Legal',
    publicPath: ['construction', 'footer', 'legal'],
    schema: editableObjectSchema,
  },
  {
    id: 'storage.anniversary-banner',
    pageId: 'storage',
    kind: 'object',
    label: 'Anniversary Banner',
    publicPath: ['storage', 'anniversary-banner'],
    schema: editableObjectSchema,
  },
  {
    id: 'storage.header',
    pageId: 'storage',
    kind: 'object',
    label: 'Header',
    publicPath: ['storage', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'storage.hero',
    pageId: 'storage',
    kind: 'object',
    label: 'Hero',
    publicPath: ['storage', 'hero'],
    schema: editableObjectSchema,
  },
  {
    id: 'storage.hero.stats',
    pageId: 'storage',
    kind: 'list',
    label: 'Hero Stats',
    publicPath: ['storage', 'hero', 'stats'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'storage.services.header',
    pageId: 'storage',
    kind: 'object',
    label: 'Services Header',
    publicPath: ['storage', 'services', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'storage.services.items',
    pageId: 'storage',
    kind: 'list',
    label: 'Services Items',
    publicPath: ['storage', 'services', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'storage.team.header',
    pageId: 'storage',
    kind: 'object',
    label: 'Team Header',
    publicPath: ['storage', 'team', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'storage.team.members',
    pageId: 'storage',
    kind: 'list',
    label: 'Team Members',
    publicPath: ['storage', 'team', 'members'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'storage.about',
    pageId: 'storage',
    kind: 'object',
    label: 'About',
    publicPath: ['storage', 'about'],
    schema: editableObjectSchema,
  },
  {
    id: 'storage.reviews.header',
    pageId: 'storage',
    kind: 'object',
    label: 'Reviews Header',
    publicPath: ['storage', 'reviews', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'storage.reviews.platforms',
    pageId: 'storage',
    kind: 'list',
    label: 'Reviews Platforms',
    publicPath: ['storage', 'reviews', 'platforms'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'storage.reviews.footer',
    pageId: 'storage',
    kind: 'object',
    label: 'Reviews Footer',
    publicPath: ['storage', 'reviews', 'footer'],
    schema: editableObjectSchema,
  },
  {
    id: 'storage.contact.header',
    pageId: 'storage',
    kind: 'object',
    label: 'Contact Header',
    publicPath: ['storage', 'contact', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'storage.contact.details',
    pageId: 'storage',
    kind: 'object',
    label: 'Contact Details',
    publicPath: ['storage', 'contact', 'details'],
    schema: editableObjectSchema,
  },
  {
    id: 'storage.footer.brand',
    pageId: 'storage',
    kind: 'object',
    label: 'Footer Brand',
    publicPath: ['storage', 'footer', 'brand'],
    schema: editableObjectSchema,
  },
  {
    id: 'storage.footer.links',
    pageId: 'storage',
    kind: 'list',
    label: 'Footer Links',
    publicPath: ['storage', 'footer', 'links'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'storage.footer.branding-options',
    pageId: 'storage',
    kind: 'list',
    label: 'Footer Branding Options',
    publicPath: ['storage', 'footer', 'branding-options'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'storage.footer.legal',
    pageId: 'storage',
    kind: 'object',
    label: 'Footer Legal',
    publicPath: ['storage', 'footer', 'legal'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.anniversary-banner',
    pageId: 'development',
    kind: 'object',
    label: 'Anniversary Banner',
    publicPath: ['development', 'anniversary-banner'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.header',
    pageId: 'development',
    kind: 'object',
    label: 'Header',
    publicPath: ['development', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.hero',
    pageId: 'development',
    kind: 'object',
    label: 'Hero',
    publicPath: ['development', 'hero'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.hero.stats',
    pageId: 'development',
    kind: 'list',
    label: 'Hero Stats',
    publicPath: ['development', 'hero', 'stats'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.land-experts.header',
    pageId: 'development',
    kind: 'object',
    label: 'Land Experts Header',
    publicPath: ['development', 'land-experts', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.land-experts.services',
    pageId: 'development',
    kind: 'list',
    label: 'Land Experts Services',
    publicPath: ['development', 'land-experts', 'services'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.land-experts.stats',
    pageId: 'development',
    kind: 'list',
    label: 'Land Experts Stats',
    publicPath: ['development', 'land-experts', 'stats'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.services.header',
    pageId: 'development',
    kind: 'object',
    label: 'Services Header',
    publicPath: ['development', 'services', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.services.items',
    pageId: 'development',
    kind: 'list',
    label: 'Services Items',
    publicPath: ['development', 'services', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.projects.categories',
    pageId: 'development',
    kind: 'list',
    label: 'Projects Categories',
    publicPath: ['development', 'projects', 'categories'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.projects.featured',
    pageId: 'development',
    kind: 'list',
    label: 'Projects Featured',
    publicPath: ['development', 'projects', 'featured'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.partners.header',
    pageId: 'development',
    kind: 'object',
    label: 'Partners Header',
    publicPath: ['development', 'partners', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.partners.items',
    pageId: 'development',
    kind: 'list',
    label: 'Partners Items',
    publicPath: ['development', 'partners', 'items'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.partners.footer',
    pageId: 'development',
    kind: 'object',
    label: 'Partners Footer',
    publicPath: ['development', 'partners', 'footer'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.team.header',
    pageId: 'development',
    kind: 'object',
    label: 'Team Header',
    publicPath: ['development', 'team', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.team.members',
    pageId: 'development',
    kind: 'list',
    label: 'Team Members',
    publicPath: ['development', 'team', 'members'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.about',
    pageId: 'development',
    kind: 'object',
    label: 'About',
    publicPath: ['development', 'about'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.about.highlights',
    pageId: 'development',
    kind: 'list',
    label: 'About Highlights',
    publicPath: ['development', 'about', 'highlights'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.about.values',
    pageId: 'development',
    kind: 'list',
    label: 'About Values',
    publicPath: ['development', 'about', 'values'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.reviews.header',
    pageId: 'development',
    kind: 'object',
    label: 'Reviews Header',
    publicPath: ['development', 'reviews', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.reviews.platforms',
    pageId: 'development',
    kind: 'list',
    label: 'Reviews Platforms',
    publicPath: ['development', 'reviews', 'platforms'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.reviews.footer',
    pageId: 'development',
    kind: 'object',
    label: 'Reviews Footer',
    publicPath: ['development', 'reviews', 'footer'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.contact.header',
    pageId: 'development',
    kind: 'object',
    label: 'Contact Header',
    publicPath: ['development', 'contact', 'header'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.contact.details',
    pageId: 'development',
    kind: 'object',
    label: 'Contact Details',
    publicPath: ['development', 'contact', 'details'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.footer.brand',
    pageId: 'development',
    kind: 'object',
    label: 'Footer Brand',
    publicPath: ['development', 'footer', 'brand'],
    schema: editableObjectSchema,
  },
  {
    id: 'development.footer.links',
    pageId: 'development',
    kind: 'list',
    label: 'Footer Links',
    publicPath: ['development', 'footer', 'links'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.footer.service-areas',
    pageId: 'development',
    kind: 'list',
    label: 'Footer Service Areas',
    publicPath: ['development', 'footer', 'service-areas'],
    schema: editableListSchema,
    listItemSchema: editableListItemSchema,
  },
  {
    id: 'development.footer.legal',
    pageId: 'development',
    kind: 'object',
    label: 'Footer Legal',
    publicPath: ['development', 'footer', 'legal'],
    schema: editableObjectSchema,
  },
] as const satisfies readonly EntityDefinition[];

export const legacyEntityDefinitions: readonly EntityDefinition[] = definitions;
export const entityDefinitions: readonly EntityDefinition[] = mergeEntityModules(definitions, [
  homeEntityModule,
  propertyManagementEntityModule,
  storageEntityModule,
]);

const pageRoutes = {
  home: '/',
  'property-management': '/property-management',
  'real-estate': '/real-estate',
  construction: '/construction',
  storage: '/storage',
  development: '/development',
} as const satisfies Record<PageId, string>;

export const pageDefinitions: readonly PageDefinition[] = pageIdSchema.options.map((id) => ({
  id,
  route: pageRoutes[id],
  s3Key: `content/pages/${id}.json`,
  entities: entityDefinitions.filter((definition) => definition.pageId === id),
}));

export const entityRegistry = new Map(
  entityDefinitions.map((definition) => [definition.id, definition] as const),
);

const uncheckedSeedData: Readonly<Record<string, unknown>> = legacyVisibleContentSeeds;
const semanticHomeSeeds: Readonly<Record<string, EditableValue>> = homeV2SeedData;
const semanticPropertyManagementSeeds: Readonly<Record<string, EditableValue>> =
  propertyManagementV2SeedData;
const semanticStorageSeeds: Readonly<Record<string, EditableValue>> = storageV2SeedData;

export const registrySeedData: Readonly<Record<EntityId, EditableValue>> = Object.fromEntries(
  entityDefinitions.map((definition) => {
    const seed =
      semanticHomeSeeds[definition.id] ??
      semanticPropertyManagementSeeds[definition.id] ??
      semanticStorageSeeds[definition.id] ??
      uncheckedSeedData[definition.id];
    definition.schema.parse(seed);
    return [definition.id, editableValueSchema.parse(seed)] as const;
  }),
);

export const LIST_ITEM_MIGRATION_NAMESPACE = 'c63b8c48-2f88-5a33-9b55-f5430eb6764a';

function fnv1a(value: string, seed: number): number {
  let hash = seed >>> 0;
  for (const character of value) {
    hash ^= character.codePointAt(0) ?? 0;
    hash = Math.imul(hash, 16_777_619);
  }
  return hash >>> 0;
}

export function deterministicListItemId(entityId: EntityId, sourcePosition: number): string {
  const input = `${LIST_ITEM_MIGRATION_NAMESPACE}:${entityId}:${sourcePosition}`;
  const words = [
    fnv1a(input, 2_166_136_261),
    fnv1a(input, 2_166_136_261 ^ 0x9e3779b9),
    fnv1a(input, 2_166_136_261 ^ 0x85ebca6b),
    fnv1a(input, 2_166_136_261 ^ 0xc2b2ae35),
  ];
  const hex = words.map((word) => word.toString(16).padStart(8, '0')).join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-5${hex.slice(13, 16)}-a${hex.slice(17, 20)}-${hex.slice(20, 32)}`;
}

export function requireEntityDefinition(id: string): EntityDefinition {
  const parsedId = entityIdSchema.parse(id);
  const definition = entityRegistry.get(parsedId);
  if (definition === undefined) {
    throw new Error(`Unknown entity ID: ${parsedId}`);
  }
  return definition;
}

export function validateRegistry(pages: readonly PageDefinition[] = pageDefinitions): void {
  const ids = new Set<string>();
  for (const page of pages) {
    for (const entity of page.entities) {
      if (entity.pageId !== page.id) {
        throw new Error(`Entity ${entity.id} has wrong pageId`);
      }
      if (ids.has(entity.id)) {
        throw new Error(`Duplicate entity ID: ${entity.id}`);
      }
      if (entity.id.split('.')[0] !== page.id) {
        throw new Error(`Entity ${entity.id} does not begin with page namespace ${page.id}`);
      }
      ids.add(entity.id);
    }
  }
}
